schemaVersion: 2.3.0
metadata:
  name: ai-in-the-loop
  tags:
    - rhas
    - jumpstarter
components:
  - name: workspace
    container:
      image: ghcr.io/rhadp/agentic-codespaces:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
      volumeMounts:
        - name: user-config
          path: /home/user/.config
        - name: user-config
          path: /home/user/.claude
  - name: user-config
    volume:
      size: 2Gi
#commands:
#  - id: init-workspace
#    exec:
#      component: workspace
#      commandLine: |
#        /usr/local/bin/init-workspace
#events:
#  postStart:
#    - init-workspace
