#FROM registry.redhat.io/devspaces/udi-base-rhel10:3.28.2
FROM quay.io/devfile/universal-developer-image:ubi10-latest

USER root

ARG TARGETARCH

# install centos stream & fedora repos, other vars
ENV ARCH=${TARGETARCH:-arm64}

# prepare for gcloud cli
RUN mkdir -p /home/tooling/.config/gcloud/logs && \
    mkdir -p /home/tooling/.config/gcloud/configurations
ENV CLOUDSDK_CONFIG=/home/tooling/.config/gcloud

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

# back to the user
USER 10001